name: Test build

on: 
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build/release Electron app
        run: npm run build
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: npm run release